[2024-03-20T05:17:12.973+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IDM_TO_BQ_PQ_RAW.stop_cluster manual__2024-03-20T05:04:30.882224+00:00 [queued]>
[2024-03-20T05:17:12.977+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IDM_TO_BQ_PQ_RAW.stop_cluster manual__2024-03-20T05:04:30.882224+00:00 [queued]>
[2024-03-20T05:17:12.977+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-20T05:17:12.982+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): stop_cluster> on 2024-03-20 05:04:30.882224+00:00
[2024-03-20T05:17:12.984+0000] {standard_task_runner.py:60} INFO - Started process 1907 to run task
[2024-03-20T05:17:12.986+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'IDM_TO_BQ_PQ_RAW', 'stop_cluster', 'manual__2024-03-20T05:04:30.882224+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/IDM_TO_BQ_PQ_RAW.py', '--cfg-path', '/tmp/tmp6wsobazb']
[2024-03-20T05:17:12.987+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask stop_cluster
[2024-03-20T05:17:12.995+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-20T05:17:13.008+0000] {task_command.py:423} INFO - Running <TaskInstance: IDM_TO_BQ_PQ_RAW.stop_cluster manual__2024-03-20T05:04:30.882224+00:00 [running]> on host bf143d508a6e
[2024-03-20T05:17:13.022+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'stop_cluster', field 'bash_command'. Template: 'end_cluster.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: end_cluster.sh
[2024-03-20T05:17:13.022+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2360, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2498, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2910, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: end_cluster.sh
[2024-03-20T05:17:13.025+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=IDM_TO_BQ_PQ_RAW, task_id=stop_cluster, execution_date=20240320T050430, start_date=20240320T051712, end_date=20240320T051713
[2024-03-20T05:17:13.029+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task stop_cluster (end_cluster.sh; 1907)
[2024-03-20T05:17:13.042+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-20T05:17:13.051+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
